name: React Pipeline
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

#      - name: Create build directory
#        run: mkdir build

      - name: Build
        run: npm run build

      - name: Upload files to Nginix webapp directory
        if: success()
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USERNAME }}
          key:  ${{ secrets.EC2_PRIVATE_KEY }}
          target: "/home/ec2-user/apps/web-app"
          source: "build"
  